### ISSUE TITLE
Start Menu Bracket Bug

### ISSUE THREAD

**Issue by mozier186** [mozier186/ComputerCraft_OS#1]
When /.menu is run and the start menu is accessed, the brackets '[ ]' around the start menu options are meant to be for 'highlight and selecting' purposes. Instead the current result is that all of the options brackets are visible, until the option is changed, then all brackets disappear.

**Comment by mozier186** [comment]
My guess is that it is somewhere in the 'drawFrontend' function.

**Comment by mozier186** [comment]
Lines 48-52 was meant to be 'nOption == 1', 'nOption == 2', 'nOption == 3', etc. for each line respectively.

**Comment by waidesoper** [comment]
You need to have a read about [scoping in Lua](https://www.lua.org/pil/4.2.html) - suffice to say, part of your problem is you are doing a comparison to an object that doesn't have a value (nOption is not declared inside the drawFrontend function)

edit: Oops, I wrote this 2 days ago and forgot to post
